### ISSUE TITLE
04_styling / image_tagにスタイルを反映できない

### ISSUE THREAD

**Issue by hasyrails** [hasyrails/newlifinancial#10]
``` ruby
# _header.html.erb
<div class="header-user-icon">
  <%= image_tag current_user.avatar.url, size: '50x50' %>
</div>
```

``` css
// application.scss
.header-user-icon{
  border-radius: 25px 25px 25px 25px;
}
```

```.header-user-icon```が丸く表示されない
